info:
  app:
    name: '@project.name@'
    version: '@project.version@'

#Server configuration
server:
  port: 8080
  servlet:
    context-path: /listening-server

#WebClient
webClient:
  timeout: 1000

#LOGGING CONFIGURATIONS
enableLoggingRequestDetails: true

debug: false
logging:
  file:
    name: server.log
    path: /opt
    max-file-size: 200MB
  logback:
    rollingpolicy:
      max-history: 30
  level:
    org:
      springframework.*: info
    com:
      crushoncod.*: debug
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-dd-MM-yyyy HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%X{UUID}){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:%4L) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    file: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-dd-MM-yyyy HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(%X{UUID}){yellow} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:%4L) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'